### ISSUE TITLE
Error al Instalar

### ISSUE THREAD

**Issue by lmoram** [nehemiascr/cabys#2]
He estado revisando este modulo y me parece excelente mis respetos.
Lo he logrado instalar pero aun no logro cargar el catalogo la ventana emergente no aparece.
A la hora de instalar se debe cambiar en nombre de la carpeta de cabys-12.0 por cabys-12 de lo contrario no deja realiazr la instalaciojn indica que no encuentra el modulo cabys-12.
Una vez relizada la instalacion no deja actualizar la base de datos la ventana emergente no se despliega.
En el log no veo nada y el unico error que veo es este.
Could not get content for /cabys/static/src/js/cabys_import_button.js defined in bundle 'web.assets_backend'.

**Comment by nehemiascr** [comment]
El error se debe a que la carpeta del módulo se debe llamar **cabys**.

El error del archivo que no puede encontrar en la ruta 

cabys/static/src/js/cabys_import_button.js

es porque se espera que la carpeta del módulo se llame cabys.

Cambiar el nombre de la carpeta a **cabys** debe de resolver el problema.

✌🏽

**Comment by lmoram** [comment]
muchas gracias lo instale de esa forma y funciono.

**Comment by nehemiascr** [comment]
Excelente y con mucho gusto ✌️
