### ISSUE TITLE
Campo CAbYs Code al importar Productos

### ISSUE THREAD

**Issue by lmoram** [nehemiascr/cabys#5]
Posterior a la instalacion no se puede importar de forma masiva listas de productos con el codigo Cabys.

**Comment by nehemiascr** [comment]
En 96b8329f83871bf439c9c82cbf6e6ac2d1c6d057 se agregó la funcionalidad de importar de manera masiva los códigos cabys, para esto se crea el id externo **cabys.codigo** donde codigo representa el codigo cabys a asignar, por ejemplo _cabys.0111100000100_ para el código 0111100000100_
